manuscript_figures:
	jupyter nbconvert --execute --to notebook --inplace figure-01.ipynb
	jupyter nbconvert --execute --to notebook --inplace figure-02.ipynb
	jupyter nbconvert --execute --to notebook --inplace figures-03-and-05.ipynb
	jupyter nbconvert --execute --to notebook --inplace figure-04.ipynb
	jupyter nbconvert --execute --to notebook --inplace figure-06.ipynb
	jupyter nbconvert --execute --to notebook --inplace figure-07.ipynb
	jupyter nbconvert --execute --to notebook --inplace figures-08-and-09.ipynb
	jupyter nbconvert --execute --to notebook --inplace figure-10.ipynb
	jupyter nbconvert --execute --to notebook --inplace metric-summary.ipynb
	jupyter nbconvert --execute --to notebook --inplace figure-11.ipynb
	jupyter nbconvert --execute --to notebook --inplace figure-12.ipynb
	jupyter nbconvert --execute --to notebook --inplace figure-S01.ipynb
